/**
 * PDF 导出器
 * 
 * 使用 PDFKit 生成格式化的 PDF 文档
 * 
 * @module exporters/pdf
 * @version 1.0.0
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');

/**
 * 导出讨论为 PDF
 */
async function exportToPDF(discussion, options = {}) {
  const {
    outputPath = null,
    includeMetadata = true,
    includeStats = true
  } = options;

  return new Promise((resolve, reject) => {
    try {
      // 创建 PDF 文档
      const doc = new PDFDocument({
        size: 'A4',
        margins: {
          top: 50,
          bottom: 50,
          left: 50,
          right: 50
        },
        info: {
          Title: discussion.topic || 'Discussion',
          Author: 'MAD - Multi-Agent Discussion',
          Subject: 'Discussion Export',
          Creator: 'MAD v2.1.0'
        }
      });

      // 收集 PDF 数据
      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);

        // 如果指定了输出路径，保存到文件
        if (outputPath) {
          fs.writeFileSync(outputPath, pdfBuffer);
        }

        resolve({
          data: pdfBuffer,
          size: pdfBuffer.length,
          path: outputPath
        });
      });

      // 添加内容
      addContent(doc, discussion, { includeMetadata, includeStats });

      // 结束文档
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * 添加内容到 PDF
 */
function addContent(doc, discussion, options) {
  const { includeMetadata, includeStats } = options;

  // 标题
  doc.fontSize(24)
     .fillColor('#1e293b')
     .text(discussion.topic || 'Discussion', { align: 'center' });
  
  doc.moveDown();

  // 元数据
  if (includeMetadata) {
    doc.fontSize(10)
       .fillColor('#64748b')
       .text(`Discussion ID: ${discussion.id}`, { align: 'center' })
       .text(`Status: ${getStatusLabel(discussion.status)}`, { align: 'center' })
       .text(`Created: ${new Date(discussion.createdAt).toLocaleString('zh-CN')}`, { align: 'center' });

    if (discussion.endedAt) {
      doc.text(`Ended: ${new Date(discussion.endedAt).toLocaleString('zh-CN')}`, { align: 'center' });
    }

    doc.moveDown();
  }

  // 分隔线
  doc.moveTo(50, doc.y)
     .lineTo(545, doc.y)
     .strokeColor('#cbd5e1')
     .lineWidth(1)
     .stroke();

  doc.moveDown();

  // 统计信息
  if (includeStats && discussion.stats) {
    doc.fontSize(14)
       .fillColor('#334155')
       .text('统计信息', { underline: true });

    doc.fontSize(10)
       .fillColor('#475569')
       .text(`消息总数: ${discussion.stats.messageCount || 0}`)
       .text(`参与 Agent: ${discussion.stats.participantCount || 0}`)
       .text(`讨论轮次: ${discussion.stats.roundCount || 0}`)
       .text(`持续时间: ${formatDuration(discussion.stats.duration)}`);

    doc.moveDown();
  }

  // 参与者列表
  if (discussion.participants && discussion.participants.length > 0) {
    doc.fontSize(14)
       .fillColor('#334155')
       .text('参与者', { underline: true });

    doc.fontSize(10)
       .fillColor('#475569');

    discussion.participants.forEach(p => {
      const line = `${p.emoji || '🤖'} ${p.role || p.name}`;
      doc.text(line, { continued: false });
    });

    doc.moveDown();
  }

  // 分隔线
  doc.moveTo(50, doc.y)
     .lineTo(545, doc.y)
     .strokeColor('#cbd5e1')
     .lineWidth(1)
     .stroke();

  doc.moveDown();

  // 消息列表
  doc.fontSize(14)
     .fillColor('#334155')
     .text('讨论记录', { underline: true });

  doc.moveDown();

  if (discussion.messages && discussion.messages.length > 0) {
    let currentRole = null;

    discussion.messages.forEach((msg, index) => {
      // 角色名称
      if (msg.role !== currentRole) {
        doc.fontSize(12)
           .fillColor('#0f172a')
           .text(`${msg.emoji || '🤖'} ${msg.role}`, { continued: false });
        currentRole = msg.role;
      }

      // 消息内容
      const content = msg.content || '';
      const lines = doc.widthOfString(content) > 495 ? wrapText(content, 495, doc) : [content];

      doc.fontSize(10)
         .fillColor('#334155')
         .list(lines);

      // 时间戳
      doc.fontSize(8)
         .fillColor('#94a3b8')
         .text(`${new Date(msg.timestamp).toLocaleString('zh-CN')}`)
         .moveDown();
    });
  } else {
    doc.fontSize(10)
       .fillColor('#94a3b8')
       .text('暂无消息');
  }

  // 页脚
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    doc.fontSize(8)
       .fillColor('#94a3b8')
       .text(
         `Generated by MAD v2.1.0 - Page ${i + 1} of ${pageCount}`,
         50,
         doc.page.height - 30,
         { align: 'center' }
       );
  }
}

/**
 * 简单的文本换行
 */
function wrapText(text, maxWidth, doc) {
  const words = text.split('');
  const lines = [];
  let currentLine = '';

  words.forEach(word => {
    const testLine = currentLine + word;
    const width = doc.widthOfString(testLine);

    if (width < maxWidth) {
      currentLine = testLine;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
  });

  if (currentLine) {
    lines.push(currentLine);
  }

  return lines;
}

/**
 * 获取状态标签
 */
function getStatusLabel(status) {
  const labels = {
    'initializing': '初始化中',
    'active': '进行中',
    'concluding': '总结中',
    'ended': '已结束'
  };
  return labels[status] || status;
}

/**
 * 格式化持续时间
 */
function formatDuration(ms) {
  if (!ms) return '未知';

  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (hours > 0) {
    return `${hours} 小时 ${minutes % 60} 分钟`;
  } else if (minutes > 0) {
    return `${minutes} 分钟 ${seconds % 60} 秒`;
  } else {
    return `${seconds} 秒`;
  }
}

module.exports = {
  exportToPDF
};
